### ISSUE TITLE
[DOCS] Usage in standalone project

### ISSUE THREAD

**Issue by christophlehmann** [networkteam/nwt-frontend-scripts#4]
Please document how to use this Neos setup in a standalone project which does not have BASE_PACKAGE_NAME and SITE_PACKAGE_NAME for example in a TYPO3 extension.

**Comment by suffle** [comment]
I updated the docs in https://github.com/networkteam/nwt-frontend-scripts/commit/fee8dddb3ffdba353b1f0b693c36edcabc4ebdfe, can you check and see if it is sufficient / understandable?
